### ISSUE TITLE
你好，你能描述一下你之前遇到的那个特殊情况么？

### ISSUE THREAD

**Issue by morisunshine** [ibireme/YYDispatchQueuePool#2]
不好意思，请原谅我的粗浅，从源码里看，这queue是一个serial队列，这样不就让这个队列失去了并发的功能了么？不是非常明白这个库的目的是在解决什么问题？

**Comment by ibireme** [comment]
每次调用 YYDispatchQueueGetForQOS() 时，随机从 pool 中取出一个 serial 队列来执行任务，这样能限制总并发数。

有时增大并发数并不能解决问题，反而会带来性能问题，具体描述可以见 readme 里的截图；这个工具只是针对这种特定情况的一个 workaround，平常的任务没必要使用。

**Comment by morisunshine** [comment]
我刚才在看- (dispatch_queue_t)queue这个方法的时候，明白了，所以关闭了这个issues，谢谢你的回复
