### ISSUE TITLE
gcd底层已经实现了线程池，有必要自己又实现一套吗？

### ISSUE THREAD

**Issue by xiongzenghuidegithub** [ibireme/YYDispatchQueuePool#9]
如题，如果真需要实现这么一套，那么最大的线程并发数请教下是如何测试的？

**Comment by ibireme** [comment]
GCD 并发队列一般来说表现足够好了。这里主要是为了避免那种 readme 中提到的，某些特殊情况下 GCD 抽风创建一大坨线程、无法控制最大并发数导致的问题。

这里创建的每个 Pool，并发数是取得 CPU 核心数，一般是用于 CPU 密集的任务。

**Comment by xiongzenghuidegithub** [comment]
恩明白了，谢谢！！！
